name=Async SHT4x
version=1.2.0
author=Xorlent
maintainer=Xorlent <https://github.com/Xorlent>
sentence=SHT4X sensor library with async support
paragraph=Enables you to use the SHT4X sensor family via I2C.
url=https://github.com/Xorlent/Async_SHT4x
category=Sensors
architectures=*
depends=Sensirion Core
